package com.studyopedia;
import java.util.*;
import java.lang.System;

public class NumberGuessGame {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub

		Scanner ob=new Scanner(System.in);
		System.out.println("!!!   Welcome To \" Guess The Number \" Challenge");
		System.out.println("The computer will generate a number from 0 to 100 and you will need to guess the number within 10(Ten) Attempts");
		System.out.println("If you fail to guess the number within given attempts you lose");
		System.out.println("One point is deducted for every wrong guess");
		
		
		int comp_gen=(int)(Math.random()*100);
		
		System.out.println("The number has been generated and your attempts begin now");
		System.out.println("---------------------------------------------------------------------------------------------------------------------------");
		
		int user_inp;
		int f=0;
		int points=10;
		
		for(int i=0;i<10;i++)
		{
			System.out.print("Enter the number that you think:-  ");
			user_inp=ob.nextInt();
			
			if(user_inp==comp_gen)
			{
				System.out.println("CONGRATULATIONS");
				System.out.println("You guessed the correct number in "+(i+1)+" attempts");
				System.out.println("Your Score is - "+points);
				f=1;
				break;
			}
			else if(user_inp>comp_gen)
				System.out.println("The number generated by the system is smaller than your guessed number");
			else if(user_inp<comp_gen)
				System.out.println("The number generated by the system is greater than your guessed number");
			points--;
		}
		if(points==0)
			System.out.println("Sorry you lost the game. You could not guess the number in the given attempts");
	}

}
